apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  labels:
    customer: drpandamd
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: drpandamd/node-app:0.2
        name: web-ctr
        ports:
        - containerPort: 8080